schemes:
  cubic:
    name: TCP Cubic
    color: black
    marker: '*'
  vegas:
    name: TCP Vegas
    color: silver
    marker: 'h'
  bbr:
    name: TCP BBR
    color: gold
    marker: '^'
  ledbat:
    name: LEDBAT
    color: green
    marker: '<'
  pcc:
    name: PCC-Allegro
    color: cadetblue
    marker: '>'
  verus:
    name: Verus
    color: skyblue
    marker: 'H'
  sprout:
    name: Sprout (95th)
    color: orange
    marker: 'p'
  sprout-75:
    name: Sprout (75th)
    color: orange
    marker: 'p'
  sprout-50:
    name: Sprout (50th)
    color: orange
    marker: 'p'
  sprout-25:
    name: Sprout (25th)
    color: orange
    marker: 'p'
  sprout-5:
    name: Sprout (5th)
    color: orange
    marker: 'p'
  sprout-0:
    name: Sprout (0th)
    color: orange
    marker: 'p'
  quic:
    name: QUIC Cubic
    color: magenta
    marker: '8'
  scream:
    name: SCReAM
    color: pink
    marker: '1'
  webrtc:
    name: WebRTC media
    color: brown
    marker: 'v'
  copa:
    name: Copa
    color: red
    marker: 'o'
  taova:
    name: TaoVA-100x
    color: gray
    marker: 'd'
  vivace:
    name: PCC-Vivace
    color: blue
    marker: '<'
  pcc_experimental:
    name: PCC-Expr
    color: olive
    marker: '<'
  fillp:
    name: FillP
    color: violet
    marker: '+'
  indigo:
    name: Indigo
    color: indigo
    marker: 'D'
  fillp_sheep:
    name: FillP-Sheep
    color: violet
    marker: 'D'
  sprout-ewma:
    name: Sprout-EWMA
    color: magenta
    marker: 'o'
  sprout-ma:
    name: Sprout-MA
    color: pink
    marker: '+'
  sprout-sewma:
    name: Sprout-SEWMA
    color: silver
    marker: 'h'
  sprout-oracle:
    name: Sprout-Oracle
    color: violet
    marker: 'D'
  sprout-fadi:
    name: Sprout-Fadi
    color: lime
    marker: 'p'
